FROM node:22-alpine

WORKDIR /app

# ติดตั้ง dependencies
COPY package.json yarn.lock ./
RUN yarn install

# copy source code
COPY . .

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

EXPOSE 3000

CMD ["yarn", "dev"]
